{
 "title": "Minepy-metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "player", "query": { "query": "mc_player_uuid" } },
   {
    "name": "server",
    "query": {
     "query": "up{job=\"minepy-metrics\"}"
    }
   }
  ]
 },
 "panels": [
  { "title": "Global infos", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mc_world_infos{instance=\"$server\"}"
    }
   ]
  },
  {
   "title": "Game mode",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mc_world_infos{instance=\"$server\"}"
    }
   ]
  },
  {
   "title": "Players online",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mc_players_online{instance=\"$server\"})"
    }
   ]
  },
  {
   "title": "Players online",
   "type": "graph",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mc_players_online{instance=\"$server\"}",
     "legendFormat": "{{player}}"
    }
   ]
  },
  {
   "title": "Difficulty",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mc_world_infos{instance=\"$server\"}"
    }
   ]
  },
  {
   "title": "Hardcore",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mc_world_infos{instance=\"$server\"}"
    }
   ]
  },
  {
   "title": "Forge",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Entities",
     "type": "stat",
     "gridPos": { "h": 7, "w": 2, "x": 0, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(mc_player_entities_loaded{instance=\"$server\"})"
      }
     ]
    },
    {
     "title": "Entities",
     "type": "graph",
     "gridPos": { "h": 7, "w": 16, "x": 2, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mc_player_entities_loaded{instance=\"$server\"}",
       "legendFormat": "{{ entity }} - {{ mod }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Global stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Deaths",
     "type": "table",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "mc_player_deaths_total{instance=\"$server\"}",
       "legendFormat": "{{player}}"
      }
     ]
    },
    {
     "title": "Kills",
     "type": "table",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(mc_player_entity_killed_total{instance=\"$server\"}) by (player)"
      }
     ]
    },
    {
     "title": "Time played",
     "type": "table",
     "gridPos": { "h": 6, "w": 4, "x": 8, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "mc_player_time_spend_total{instance=\"$server\", action=\"played\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "$player stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "repeat": "player",
   "collapsed": true,
   "panels": [
    {
     "title": "Status",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mc_player_health{instance=\"$server\", player=\"$player\"}",
       "legendFormat": "Health"
      },
      {
       "expr": "mc_player_food_level{instance=\"$server\", player=\"$player\"}",
       "legendFormat": "Food"
      },
      {
       "expr": "mc_player_food_saturation_level{instance=\"$server\", player=\"$player\"}",
       "legendFormat": "Food saturation"
      }
     ]
    },
    {
     "title": "Play time",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 4, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mc_player_time_spend_total{instance=\"$server\", player=\"$player\", action=\"played\"}"
      }
     ]
    },
    {
     "title": "Score",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 6, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mc_player_score{instance=\"$server\", player=\"$player\"}"
      }
     ]
    },
    {
     "title": "Kills",
     "type": "table",
     "gridPos": { "h": 6, "w": 6, "x": 8, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "mc_player_entity_killed_total{instance=\"$server\", player=\"$player\"}"
      }
     ]
    },
    {
     "title": "Traveled",
     "type": "table",
     "gridPos": { "h": 6, "w": 4, "x": 14, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "lengthm" } },
     "targets": [
      {
       "expr": "mc_player_distance_total{instance=\"$server\", player=\"$player\"}/100"
      }
     ]
    },
    {
     "title": "Crafted",
     "type": "table",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "mc_player_crafted_total{instance=\"$server\", player=\"$player\"}"
      }
     ]
    },
    {
     "title": "Level",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 4, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "mc_player_xp_level{instance=\"$server\", player=\"$player\"}"
      }
     ]
    },
    {
     "title": "Jump",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 6, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mc_player_jump_total{instance=\"$server\", player=\"$player\"}"
      }
     ]
    },
    {
     "title": "Items enchanted",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "mc_player_item_enchanted_total{instance=\"$server\", player=\"$player\"}"
      }
     ]
    },
    {
     "title": "Leave game",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 2, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mc_player_leave_game_total{instance=\"$server\", player=\"$player\"}"
      }
     ]
    },
    {
     "title": "Damage dealt",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 4, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mc_player_damage_dealt_total{instance=\"$server\", player=\"$player\"}"
      }
     ]
    },
    {
     "title": "Entity killed",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 6, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(mc_player_entity_killed_total{instance=\"$server\", player=\"$player\"})"
      }
     ]
    },
    {
     "title": "Deaths by mobs",
     "type": "table",
     "gridPos": { "h": 6, "w": 6, "x": 8, "y": 23 },
     "targets": [
      {
       "expr": "mc_player_killed_by_total{instance=\"$server\", player=\"$player\"}",
       "legendFormat": "{{killer}}"
      }
     ]
    },
    {
     "title": "Interactions",
     "type": "table",
     "gridPos": { "h": 6, "w": 4, "x": 14, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "mc_player_interacted_total{instance=\"$server\", player=\"$player\"}"
      }
     ]
    },
    {
     "title": "Used",
     "type": "table",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "mc_player_used_total{instance=\"$server\", player=\"$player\"}"
      }
     ]
    },
    {
     "title": "Fish caught",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mc_player_fish_caught_total{instance=\"$server\", player=\"$player\"}"
      }
     ]
    },
    {
     "title": "Damage taken",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 4, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mc_player_damage_taken_total{instance=\"$server\", player=\"$player\"}"
      }
     ]
    },
    {
     "title": "Mined",
     "type": "table",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "mc_player_mined_total{instance=\"$server\", player=\"$player\"}"
      }
     ]
    },
    {
     "title": "Broke",
     "type": "table",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "mc_player_broken_total{instance=\"$server\", player=\"$player\"}"
      }
     ]
    },
    {
     "title": "Picked up",
     "type": "table",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "mc_player_picked_up_total{instance=\"$server\", player=\"$player\"}"
      }
     ]
    }
   ]
  }
 ]
}